### PR TITLE
Add default example sandbox for CodeSandbox CI

### PR DESCRIPTION
**Pull request by CompuIves**

### CODE REVIEW

**Comment by InventingWithMonster** [comment]
Excellent thanks Ives and for checking out whatever was breaking!

**Comment by Sh00k-ThaD3v** [comment]
yay

**Comment by luisenriquecorona** [comment]
Prueba para mí código.

**Comment by Adawntoremember** [comment]
Easy as pie

**Comment by IVEN-CHEN** [comment]
[](url)

**Comment by IVEN-CHEN** [comment]
CompuIves:patch-1

**Comment by msulikowski96-cmd** [comment]
B

**Pull request merged**
